displayManager: sddm
basicSetup:     false

desktops:
  - name:        Plasma
    desktopFile: plasma
    executable:  /usr/bin/startplasma-wayland
    xsession:    plasma

  - name:        GNOME
    desktopFile: gnome
    executable:  /usr/bin/gnome-session
    xsession:    gnome

  - name:        Hyprland
    desktopFile: hyprland
    executable:  /usr/bin/Hyprland
    xsession:    hyprland

defaultDesktopEnvironment:
  executable:  /usr/bin/startplasma-wayland
  desktopFile: plasma
