mountOptions:
  - filesystem: btrfs
    options:     defaults,noatime,compress=zstd,space_cache=v2
  - filesystem: ext4
    options:     defaults,noatime
  - filesystem: vfat
    options:     umask=0077
  - filesystem: tmpfs
    options:     defaults,noatime,mode=0755

swapmountpoint: /swap
