backend: pacman

# netinstall module handles DE package installation.
# This module handles cleanup of live-only packages.

operations:
  - remove:
    - calamares
    - mkinitcpio-archiso
    - archinstall
    - clonezilla
    - squashfs-tools
    - livecd-sounds
    - brltty
    - espeakup
