backend: pacman

operations:
  - remove:
    # Live ISO tools not needed on installed system
    - calamares
    - mkinitcpio-archiso
    - archinstall
    - clonezilla
    - squashfs-tools
    - livecd-sounds
    - brltty
    - espeakup
