efi:
  mountPoint:       /boot/efi
  recommendedSize:  512MiB
  minimumSize:      300MiB

userSwapChoices:
  - none
  - small
  - suspend
  - file

requiredStorage: 20

defaultFileSystemType: "btrfs"

availableFileSystemTypes:
  - ext4
  - btrfs
  - xfs
