#
# /etc/pacman.conf — Haifa OS
#

[options]
HoldPkg           = pacman glibc
Architecture      = auto
ParallelDownloads = 5
SigLevel          = Required DatabaseOptional
LocalFileSigLevel = Optional
Color
VerbosePkgLists
CheckSpace

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS — performance kernel, gamescope, and more
# Requires: cachyos-keyring package
[cachyos]
Server = https://mirror.cachyos.org/repo/x86_64/$repo
SigLevel = Optional TrustAll

# Haifa OS repo — branding, meta packages, defaults
# [haifaos]
# Server = https://repo.haifaos.org/$arch
# SigLevel = Optional TrustAll
