modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - hostname
    - netinstall
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - initcpio
    - users
    - hostname
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - grubcfg
    - bootloader
    - shellprocess-post
    - preservefiles
    - umount
  - show:
    - finished

branding: haifaos

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false
